name: CodeCov Baseline Publish

on:
  push:
    branches:
      - 'dev'
jobs:
  codecov-baseline-publish:
    name: Publish codecov baseline for dev
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd BrickKit && ./gradlew connectedCheck

      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
